version: "3"
services:
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    volumes:
      - ./:/home/finder
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - redis
    environment:
      - REDIS_HOSTNAME=redis 
      - REDIS_PORT=6379
